### ISSUE TITLE
Messed up sidebar on small-ish (600px) screen height

### ISSUE THREAD

**Issue by mik13ST** [RobertLemmens/youtube-sync#1]
I use an old ThinkPad with screen resolution of 1280x800 and the sidebar doesn't fit the screen. I don't know Scala at all, but I know HTML and CSS well, are contributions welcome?

![image](https://user-images.githubusercontent.com/19293769/108417676-90e73400-7230-11eb-89dd-44ded9ddd5fb.png)

**Comment by RobertLemmens** [comment]
Hey, contributions are most certainly welcome! It's been a while since ive done any updates here. The html/css for the page is a single html file found here:
https://github.com/RobertLemmens/youtube-sync/blob/master/backend/src/main/resources/web/index.html

I created this project partly to have a go at ScalaJS, this means that most javascript is generated by scala code. The arrow that collapses the side panel for example, is done in Scala. Im not sure how that will affect the changes you'd like to make, but keep that in mind 👍  If need be i can take a look at it when i have some time later this week, the sidepanel does look funky on small screens indeed.

**Comment by mik13ST** [comment]
Good. I did some research whether I need to know Scala or ScalaJS for that fix and it seemed like I don't. I already tried to fix it. It seems editing the index.html file should be all there is needed. The change should be under 5 rows in size. I might do a PR then.
