### ISSUE TITLE
Why not have a Docker builder?

### ISSUE THREAD

**Issue by mik13ST** [RobertLemmens/youtube-sync#6]
I'd like to be able to compile and run the project on my machine without the knowledge of the Scala tools. I noticed you recently added a Dockerfile and it seems to handle running a compiled .jar only. I'd like to contribute a Dockerfile that compiles the project without relying on any tools available on the system. Maybe these two could be merged into one. I don't know, I want to practice Docker and find out what's best.

This would make it easier for web developers (me) to contribute and see their changes before making a PR.

**Comment by RobertLemmens** [comment]
This is a good idea, i will try to build one soon.

**Comment by RobertLemmens** [comment]
made a small beginning on this that ive tested on a linux machine. The script is simple, and utilizes a docker image prebuild by mozilla (mozilla/sbt) that contains all the tools needed. It first builds the jar using mozilla/sbt and then builds a docker image for the application itself. It should be run from the root of the project directory, because it mounts the current directory to the container.

The commands run are:
```
docker run -it --rm -v $PWD:/app -w /app mozilla/sbt sbt "project backend" assembly 
docker build -t rlemmens/youtube-sync:latest .                                           
```

I might come back and improve upon it later, maybe caching dependencies and whatnot to speed up the process. If you got any ideas to make it more easy to use, let me know 👍

**Comment by mik13ST** [comment]
Yes, this works. 

I think you should also mention a way to run the container, because people unfamiliar with docker will find that difficult at first. I used `docker run -it --rm -p 127.0.0.1:8080:8080 --name ytsync rlemmens/youtube-sync` which I ran after running `./build.sh`. Maybe create `run.sh` then? Or maybe use `docker-compose` instead? I don't know.

Yes, the rebuild takes a considerable amount of time this way, but this works for now.

**Comment by RobertLemmens** [comment]
Nice, Ive now also added a run.sh which should run the container in pr #9 and updated the readme.
